# Run locally with: pre-commit install && pre-commit run --all-files
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        exclude: ^deploy/.*\.yaml$
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff-format
        files: ^backend/(app|scripts)/.*\.py$
      - id: ruff
        args: [--fix]
        files: ^backend/(app|scripts)/.*\.py$
