/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubmitIndexRouteImport } from './routes/submit/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SubmitMyRouteImport } from './routes/submit/my'
import { Route as PasswordResetRouteImport } from './routes/password.reset'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as AppsAppIdRouteImport } from './routes/apps/$appId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUpdatesRouteImport } from './routes/admin/updates'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminSecretsRouteImport } from './routes/admin/secrets'
import { Route as AdminLicensesRouteImport } from './routes/admin/licenses'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as AdminInstallersRouteImport } from './routes/admin/installers'
import { Route as AdminGpusRouteImport } from './routes/admin/gpus'
import { Route as AdminChangeRequestsRouteImport } from './routes/admin/change-requests'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAgentsRouteImport } from './routes/admin/agents'
import { Route as AppsAppIdRunRouteImport } from './routes/apps/$appId.run'
import { Route as AdminChangeRequestsCrIdRouteImport } from './routes/admin/change-requests.$crId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitIndexRoute = SubmitIndexRouteImport.update({
  id: '/submit/',
  path: '/submit/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitMyRoute = SubmitMyRouteImport.update({
  id: '/submit/my',
  path: '/submit/my',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password/reset',
  path: '/password/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdRoute = AppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUpdatesRoute = AdminUpdatesRouteImport.update({
  id: '/admin/updates',
  path: '/admin/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecretsRoute = AdminSecretsRouteImport.update({
  id: '/admin/secrets',
  path: '/admin/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLicensesRoute = AdminLicensesRouteImport.update({
  id: '/admin/licenses',
  path: '/admin/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstallersRoute = AdminInstallersRouteImport.update({
  id: '/admin/installers',
  path: '/admin/installers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGpusRoute = AdminGpusRouteImport.update({
  id: '/admin/gpus',
  path: '/admin/gpus',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChangeRequestsRoute = AdminChangeRequestsRouteImport.update({
  id: '/admin/change-requests',
  path: '/admin/change-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdRunRoute = AppsAppIdRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => AppsAppIdRoute,
} as any)
const AdminChangeRequestsCrIdRoute = AdminChangeRequestsCrIdRouteImport.update({
  id: '/$crId',
  path: '/$crId',
  getParentRoute: () => AdminChangeRequestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/change-requests': typeof AdminChangeRequestsRouteWithChildren
  '/admin/gpus': typeof AdminGpusRoute
  '/admin/installers': typeof AdminInstallersRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/secrets': typeof AdminSecretsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/updates': typeof AdminUpdatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/apps/$appId': typeof AppsAppIdRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/password/reset': typeof PasswordResetRoute
  '/submit/my': typeof SubmitMyRoute
  '/admin/': typeof AdminIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/submit/': typeof SubmitIndexRoute
  '/admin/change-requests/$crId': typeof AdminChangeRequestsCrIdRoute
  '/apps/$appId/run': typeof AppsAppIdRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/change-requests': typeof AdminChangeRequestsRouteWithChildren
  '/admin/gpus': typeof AdminGpusRoute
  '/admin/installers': typeof AdminInstallersRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/secrets': typeof AdminSecretsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/updates': typeof AdminUpdatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/apps/$appId': typeof AppsAppIdRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/password/reset': typeof PasswordResetRoute
  '/submit/my': typeof SubmitMyRoute
  '/admin': typeof AdminIndexRoute
  '/apps': typeof AppsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/submit': typeof SubmitIndexRoute
  '/admin/change-requests/$crId': typeof AdminChangeRequestsCrIdRoute
  '/apps/$appId/run': typeof AppsAppIdRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/change-requests': typeof AdminChangeRequestsRouteWithChildren
  '/admin/gpus': typeof AdminGpusRoute
  '/admin/installers': typeof AdminInstallersRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/secrets': typeof AdminSecretsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/updates': typeof AdminUpdatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/apps/$appId': typeof AppsAppIdRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/password/reset': typeof PasswordResetRoute
  '/submit/my': typeof SubmitMyRoute
  '/admin/': typeof AdminIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/submit/': typeof SubmitIndexRoute
  '/admin/change-requests/$crId': typeof AdminChangeRequestsCrIdRoute
  '/apps/$appId/run': typeof AppsAppIdRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/admin/agents'
    | '/admin/audit'
    | '/admin/change-requests'
    | '/admin/gpus'
    | '/admin/installers'
    | '/admin/integrations'
    | '/admin/licenses'
    | '/admin/secrets'
    | '/admin/services'
    | '/admin/submissions'
    | '/admin/updates'
    | '/admin/users'
    | '/apps/$appId'
    | '/jobs/$jobId'
    | '/password/reset'
    | '/submit/my'
    | '/admin/'
    | '/apps/'
    | '/jobs/'
    | '/submit/'
    | '/admin/change-requests/$crId'
    | '/apps/$appId/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/admin/agents'
    | '/admin/audit'
    | '/admin/change-requests'
    | '/admin/gpus'
    | '/admin/installers'
    | '/admin/integrations'
    | '/admin/licenses'
    | '/admin/secrets'
    | '/admin/services'
    | '/admin/submissions'
    | '/admin/updates'
    | '/admin/users'
    | '/apps/$appId'
    | '/jobs/$jobId'
    | '/password/reset'
    | '/submit/my'
    | '/admin'
    | '/apps'
    | '/jobs'
    | '/submit'
    | '/admin/change-requests/$crId'
    | '/apps/$appId/run'
  id:
    | '__root__'
    | '/'
    | '/download'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/admin/agents'
    | '/admin/audit'
    | '/admin/change-requests'
    | '/admin/gpus'
    | '/admin/installers'
    | '/admin/integrations'
    | '/admin/licenses'
    | '/admin/secrets'
    | '/admin/services'
    | '/admin/submissions'
    | '/admin/updates'
    | '/admin/users'
    | '/apps/$appId'
    | '/jobs/$jobId'
    | '/password/reset'
    | '/submit/my'
    | '/admin/'
    | '/apps/'
    | '/jobs/'
    | '/submit/'
    | '/admin/change-requests/$crId'
    | '/apps/$appId/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadRoute: typeof DownloadRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminChangeRequestsRoute: typeof AdminChangeRequestsRouteWithChildren
  AdminGpusRoute: typeof AdminGpusRoute
  AdminInstallersRoute: typeof AdminInstallersRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLicensesRoute: typeof AdminLicensesRoute
  AdminSecretsRoute: typeof AdminSecretsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminUpdatesRoute: typeof AdminUpdatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AppsAppIdRoute: typeof AppsAppIdRouteWithChildren
  JobsJobIdRoute: typeof JobsJobIdRoute
  PasswordResetRoute: typeof PasswordResetRoute
  SubmitMyRoute: typeof SubmitMyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppsIndexRoute: typeof AppsIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  SubmitIndexRoute: typeof SubmitIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/': {
      id: '/submit/'
      path: '/submit'
      fullPath: '/submit/'
      preLoaderRoute: typeof SubmitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/my': {
      id: '/submit/my'
      path: '/submit/my'
      fullPath: '/submit/my'
      preLoaderRoute: typeof SubmitMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/reset': {
      id: '/password/reset'
      path: '/password/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId': {
      id: '/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/updates': {
      id: '/admin/updates'
      path: '/admin/updates'
      fullPath: '/admin/updates'
      preLoaderRoute: typeof AdminUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/secrets': {
      id: '/admin/secrets'
      path: '/admin/secrets'
      fullPath: '/admin/secrets'
      preLoaderRoute: typeof AdminSecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/licenses': {
      id: '/admin/licenses'
      path: '/admin/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AdminLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/installers': {
      id: '/admin/installers'
      path: '/admin/installers'
      fullPath: '/admin/installers'
      preLoaderRoute: typeof AdminInstallersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gpus': {
      id: '/admin/gpus'
      path: '/admin/gpus'
      fullPath: '/admin/gpus'
      preLoaderRoute: typeof AdminGpusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/change-requests': {
      id: '/admin/change-requests'
      path: '/admin/change-requests'
      fullPath: '/admin/change-requests'
      preLoaderRoute: typeof AdminChangeRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId/run': {
      id: '/apps/$appId/run'
      path: '/run'
      fullPath: '/apps/$appId/run'
      preLoaderRoute: typeof AppsAppIdRunRouteImport
      parentRoute: typeof AppsAppIdRoute
    }
    '/admin/change-requests/$crId': {
      id: '/admin/change-requests/$crId'
      path: '/$crId'
      fullPath: '/admin/change-requests/$crId'
      preLoaderRoute: typeof AdminChangeRequestsCrIdRouteImport
      parentRoute: typeof AdminChangeRequestsRoute
    }
  }
}

interface AdminChangeRequestsRouteChildren {
  AdminChangeRequestsCrIdRoute: typeof AdminChangeRequestsCrIdRoute
}

const AdminChangeRequestsRouteChildren: AdminChangeRequestsRouteChildren = {
  AdminChangeRequestsCrIdRoute: AdminChangeRequestsCrIdRoute,
}

const AdminChangeRequestsRouteWithChildren =
  AdminChangeRequestsRoute._addFileChildren(AdminChangeRequestsRouteChildren)

interface AppsAppIdRouteChildren {
  AppsAppIdRunRoute: typeof AppsAppIdRunRoute
}

const AppsAppIdRouteChildren: AppsAppIdRouteChildren = {
  AppsAppIdRunRoute: AppsAppIdRunRoute,
}

const AppsAppIdRouteWithChildren = AppsAppIdRoute._addFileChildren(
  AppsAppIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadRoute: DownloadRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminChangeRequestsRoute: AdminChangeRequestsRouteWithChildren,
  AdminGpusRoute: AdminGpusRoute,
  AdminInstallersRoute: AdminInstallersRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLicensesRoute: AdminLicensesRoute,
  AdminSecretsRoute: AdminSecretsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminUpdatesRoute: AdminUpdatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AppsAppIdRoute: AppsAppIdRouteWithChildren,
  JobsJobIdRoute: JobsJobIdRoute,
  PasswordResetRoute: PasswordResetRoute,
  SubmitMyRoute: SubmitMyRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppsIndexRoute: AppsIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  SubmitIndexRoute: SubmitIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
